---
openapi: 3.0.2
info:
  title: Simple
  version: 1.0.0
paths:
  /client:
    get:
      summary: Get list of client
      operationId: list
      responses:
        200:
          description: Return client list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
components:
  schemas:
    Client:
      type: object
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
